name: River Stone
favicon: null
layout_spectrum: 0.3473362419754267
typography_spectrum: 0.00321682495996356
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7437119300011545
  lightness: 0.539025169564411
  saturation: 0.32351405126973987
  rhythmicContrast: 0.5477588791400194
purpose: []
